### ISSUE TITLE
Errors in generated code when names of elements consist of multiple words with spaces between them

### ISSUE THREAD

**Issue by qbicsky** [niklauslee/staruml-python#13]
### Steps to replicate
1. Create a Class diagram with at least one element.
2. Name this element with at least two words name (ie. Person Of Interest)
3. Generate code from this diagram

### Alternative path
For step 2. you can also use the same naming convention for model/package name - results with bugs (especially in inheritances)

edit: I can try to fix this by myself. But i don't know how to assign myself to this issue.

**Comment by IvanMtze** [comment]
Do you mean using underscore instead of spaces on python generated code?

**Comment by qbicsky** [comment]
Well, for functions (operations) it would be underscore. For Classes it would be CapWords (CamelCase with Capital initial character) and so on. All based on PEP8. For future compatibility I would recommend doing this with configuration.
As I’ve mentioned, I can try to address this issue by myself. 😉

Jakub.

**Comment by IvanMtze** [comment]
Feel free to create a PR if you have something done.
