### ISSUE TITLE
Enhance compliance with PEP8

### ISSUE THREAD

**Issue by cfq20** [niklauslee/staruml-python#4]
The Python modules produced by this StarUML extension should be modified to comply with the PEP8 specification by:
1. leaving 2 blank lines before each class declaration;
2. removing trailing blank line at the end of file.

**Comment by arcturus140** [comment]
I get a 
> block comment should start with '# '

note for `#-*- coding: utf-8 -*-`

please also add a space after `#`:
`# -*- coding: utf-8 -*-`

**Comment by IvanMtze** [comment]
Hi @arcturus140 . As PEP 263 in Python documentation page suggest, it is a good idea to include encoding specification. Unfortunately, this practice is recommended only on Python 2.*. In newer versions of python, the default encoding is etf-8. Though, I will be working on this issue to make it work properly. If you need more information about pep 263, I added a link to documentation page. 
https://www.python.org/dev/peps/pep-0263/ 

@cfq20 Thank you for the advice. I will be working on this, so please make sure you have the latest version of this tool.

**Comment by IvanMtze** [comment]
Please, download for the newer version. 

- [x] removing trailing blank line at the end of file.
- [x] leaving 2 blank lines before each class declaration;
- [x] added space before encoding header
