### ISSUE TITLE
Became a new manteiner

### ISSUE THREAD

**Issue by IvanMtze** [niklauslee/staruml-python#8]
Hi, I would like to help this project. What can I do for it?

**Comment by niklauslee** [comment]
Thank you @IvanMtze  for your voluntary. 👍 

Now you are invited as a collaborator in this repository, so you can contribute without any permissions by committing or merging PRs. When you contribute enough to be a sole maintainer, we will transfer this repository to your account.

Thank you.

**Comment by IvanMtze** [comment]
OK @niklauslee 
I will be adding  a Kanban board on project part and other things before moving on programming. I guess it's a good idea so you will be able to check what I working on. If there is any suggestion, please let me know.
Once again, thank you.
